[workspace]
pr_branch_prefix = "release-plz-"
# Only publish when the release PR is merged
# https://release-plz.dev/docs/config#the-release_always-field
release_always = false
# Create a GitHub release when a release is published
# https://release-plz.dev/docs/config#the-git_release_enable-field
git_release_enable = true
# Create a Git tag for releases
# https://release-plz.dev/docs/config#the-git_tag_enable-field
git_tag_enable = true
